[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "Stoker"
versionNumber = "0.0.2"
description = "Cheat Manager and Console"
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/StokerCheatConsole"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.2.9"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


